{% set name = "datalab-kernel" %}
{% set version = "0.2.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datalab_kernel/datalab_kernel-{{ version }}.tar.gz
  sha256: 9c8d4b4a87ddbb80c881c87cbf51bbb20faf51f4b66e5b6f4115609dfda980ac

build:
  entry_points:
    - datalab-kernel-install = datalab_kernel.install:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - xeus-python >=0.17.0
    - xeus-python-shell >=0.6.0
    - numpy >=1.22
    - httpx >=0.25.0
    - h5py >=3.0
    - matplotlib-base >=3.5
    - sigima >=1.0

test:
  imports:
    - datalab_kernel
  commands:
    - datalab-kernel-install --help
    - pytest --collect-only --pyargs datalab_kernel.tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/DataLab-Platform/DataLab-Kernel
  summary: A standalone Jupyter kernel for DataLab with optional live synchronization
  doc_url: https://datalab-kernel.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
